name: Docker Image CI

on:
  push:
  workflow_dispatch:

env:
  DOCKER_USERNAME: slothcroissant
  DOCKER_CONTAINER_NAME: nfs-server-alpine
  DOCKER_TARGET_PLATFORM: linux/amd64

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=tag::$(date +%Y.%m.%d-$GITHUB_RUN_NUMBER)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: ${{ steps.prepare.outputs.docker_platform }}
        push: true
        tags: |
          ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
          ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
